[project]
name = "clide-demo"
version = "0.1.4"

[tool.mlton]
common_flags = []
dev_flags = []
prod_flags = []

[[bin]]
name = "clide-demo"
out_name = "clide-demo"

[mlb.clide-demo]
base = "mlb/clide-demo-base.mlb"
dev = "mlb/clide-demo-dev.mlb"
prod = "mlb/clide-demo-prod.mlb"
test = "mlb/clide-demo-test.mlb"
