[project]
name = "clide-demo"
version = "0.1.4"

[tool.mlton]
common_flags = []
dev_flags = ["-const", "'Exn.keepHistory true'"]
prod_flags = []

[[bin]]
name = "clide-demo"
out_name = "clide"

[mlb.clide-demo]
base = "mlb/clide-base.mlb"
dev = "mlb/clide-dev.mlb"
prod = "mlb/clide-prod.mlb"
test = "mlb/clide-test.mlb"
